<?php
function getClasse($id) {

        $classes = [
            0    => 'Aprendiz',
            1    => 'Espadachim',
            2    => 'Mago',
            3    => 'Arqueiro',
            4    => 'Noviço',
            5    => 'Mercador',
            6    => 'Gatuno',
            7    => 'Cavaleiro',
            8    => 'Sacerdote',
            9    => 'Bruxo',
            10   => 'Ferreiro',
            11   => 'Caçador',
            12   => 'Mercenário',
        //13   => 'Cavaleiro (Peco)',
            14   => 'Templário',
            15   => 'Monge',
            16   => 'Sábío',
            17   => 'Arruaceiro',
            18   => 'Alquimista',
            19   => 'Bardo',
            20   => 'Odalisca',
        //21   => 'Templário (Peco)',
            22   => 'Casamento',
            23   => 'Super Aprendiz',
            24   => 'Justiceiro',
            25   => 'Ninja',
            26   => 'Xmas',
            27   => 'Summer',
            28   => 'Hanbok',
            29   => 'Oktoberfest',

            4001 => 'Aprendiz T.',
            4002 => 'Espadachim T.',
            4003 => 'Mago T.',
            4004 => 'Arqueiro T.',
            4005 => 'Noviço T.',
            4006 => 'Mercador T.',
            4007 => 'Gatuno T.',
            4008 => 'Lorde',
            4009 => 'Sumo-Sacerdote',
            4010 => 'Arquimago',
            4011 => 'Mestre-Ferreiro',
            4012 => 'Atirador de Elite',
            4013 => 'Algoz',
        //4014 => 'Lorde (Peco)',
            4015 => 'Paladino',
            4016 => 'Mestre',
            4017 => 'Professor',
            4018 => 'Desordeiro',
            4019 => 'Criador',
            4020 => 'Menestrel',
            4021 => 'Cigana',
        //4022 => 'Paladino (Peco)',

            4023 => 'Bebê',
            4024 => 'Espadachim Bebê',
            4025 => 'Mago Bebê',
            4026 => 'Arqueiro Bebê',
            4027 => 'Noviço Bebê',
            4028 => 'Mercador Bebê',
            4029 => 'Gatuno Bebê',
            4030 => 'Cavaleiro Bebê',
            4031 => 'Sacerdote Bebê',
            4032 => 'Bruxo Bebê',
            4033 => 'Ferreiro Bebê',
            4034 => 'Caçador Bebê',
            4035 => 'Mercenário Bebê',
        //4036 => 'Cavaleiro Bebê (Peco)',
            4037 => 'Templário Bebê',
            4038 => 'Monge Bebê',
            4039 => 'Sábio Bebê',
            4040 => 'Arruaceiro Bebê',
            4041 => 'Alquimista Bebê',
            4042 => 'Bardo Bebê',
            4043 => 'Odalisca Bebê',
        //4044 => 'Templário Bebê (Peco)',
            4045 => 'Super Aprendiz Bebê',

            4046 => 'Taekwon',
            4047 => 'Mestre Taekwon',
        //4048 => 'Mestre Taekwon (Voo)',
            4049 => 'Espiritualista',

            4050 => 'Jiang Shi',
            4051 => 'Death Knight',
            4052 => 'Dark Collector',

            4054 => 'Cavaleiro Rúnico',
            4055 => 'Arcano',
            4056 => 'Sentinela',
            4057 => 'Arcebispo',
            4058 => 'Mecânico',
            4059 => 'Sicário',
            4060 => 'Cavaleiro Rúnico T.',
            4061 => 'Arcano T.',
            4062 => 'Sentinela T.',
            4063 => 'Arcebispo T.',
            4064 => 'Mecânico T.',
            4065 => 'Sicário T.',
            4066 => 'Guardião Real',
            4067 => 'Feiticeiro',
            4068 => 'Trovador',
            4069 => 'Musa',
            4070 => 'Shura',
            4071 => 'Bioquímico',
            4072 => 'Renegado',
            4073 => 'Guardião Real T.',
            4074 => 'Feiticeiro T.',
            4075 => 'Trovador T.',
            4076 => 'Musa T.',
            4077 => 'Shura T.',
            4078 => 'Bioquímico T.',
            4079 => 'Renegado T.',

        //4080 => 'Cavaleiro Rúnico (Dragão)',
        //4081 => 'Cavaleiro Rúnico T. (Dragão)',
        //4082 => 'Guardião Real (Grifo)',
        //4083 => 'Guardião Real T. (Grifo)',
        //4084 => 'Sentinela (Lobo)',
        //4085 => 'Sentinela T. (Lobo)',
        //4086 => 'Mecânico (Robô)',
        //4087 => 'Mecânico T. (Robô)',

            4096 => 'Cavaleiro Rúnico Bebê',
            4097 => 'Arcano Bebê',
            4098 => 'Sentinela Bebê',
            4099 => 'Arcebispo Bebê',
            4100 => 'Mecânico Bebê',
            4101 => 'Sicário Bebê',
            4102 => 'Guardião Real Bebê',
            4103 => 'Feiticeiro Bebê',
            4104 => 'Trovador Bebê',
            4105 => 'Musa Bebê',
            4106 => 'Shura Bebê',
            4107 => 'Bioquímico Bebê',
            4108 => 'Renegado Bebê',

        //4109 => 'Cavaleiro Rúnico Bebê (Dragão)',
        //4110 => 'Guardião Real Bebê (Grifo)',
        //4111 => 'Sentinela Bebê (Lobo)',
        //4112 => 'Mecânico Bebê (Robô)',

            4190 => 'Super Aprendiz T.',
            4191 => 'Super Aprendiz Bebê T.',

            4211 => 'Kagerou',
            4212 => 'Oboro',

            4215 => 'Rebelde',
            4218 => 'Summoner',

            4220 => 'Summoner Bebê',
            4222 => 'Ninja Bebê',
            4223 => 'Kagero Bebê',
            4224 => 'Oboro Bebê',
            4225 => 'Taekwon Bebê',
            4226 => 'Mestre Taekwon Bebê',
            4227 => 'Espiritualista Bebê',
            4228 => 'Justiceiro Bebê',
            4229 => 'Rebellion Bebê',
        //4238 => 'Mestre Taekwon Bebê (União)',

        //4238 => 'Mestre Taekwon Bebê (União)',
            4239 => 'Star Emperor',
            4240 => 'Soul Reaper',
            4241 => 'Bebê Star Emperor',
            4242 => 'Bebê Soul Reaper',

            4252 => 'Dragon Knight',
            4253 => 'Meister',
            4254 => 'Shadow Cross',
            4255 => 'Arch Mage',
            4256 => 'Cardinal',
            4257 => 'WindHawk',
            4258 => 'Imperial Guard',
            4259 => 'Biolo',
            4260 => 'Abyss Chaser',
            4261 => 'Elemental Master',
            4262 => 'Inquisitor',
            4263 => 'Troubadour',
            4264 => 'Trouvere',
        ];

        return $classes[$id] ?? 'Desconhecida';

    } 
function Jobs(){
         return  [
            0    => 'Aprendiz',
            1    => 'Espadachim',
            2    => 'Mago',
            3    => 'Arqueiro',
            4    => 'Noviço',
            5    => 'Mercador',
            6    => 'Gatuno',
            7    => 'Cavaleiro',
            8    => 'Sacerdote',
            9    => 'Bruxo',
            10   => 'Ferreiro',
            11   => 'Caçador',
            12   => 'Mercenário',
        //13   => 'Cavaleiro (Peco)',
            14   => 'Templário',
            15   => 'monge',
            16   => 'Sábío',
            17   => 'Arruaceiro',
            18   => 'Alquimista',
            19   => 'Bardo',
            20   => 'Odalisca',
        //21   => 'Templário (Peco)',
            22   => 'Casamento',
            23   => 'Super Aprendiz',
            24   => 'Justiceiro',
            25   => 'Ninja',
            26   => 'Xmas',
            27   => 'Summer',
            28   => 'Hanbok',
            29   => 'Oktoberfest',

            4001 => 'Aprendiz T.',
            4002 => 'Espadachim T.',
            4003 => 'Mago T.',
            4004 => 'Arqueiro T.',
            4005 => 'Noviço T.',
            4006 => 'Mercador T.',
            4007 => 'Gatuno T.',
            4008 => 'Lorde',
            4009 => 'Sumo-Sacerdote',
            4010 => 'Arquimago',
            4011 => 'Mestre-Ferreiro',
            4012 => 'Atirador de Elite',
            4013 => 'Algoz',
        //4014 => 'Lorde (Peco)',
            4015 => 'Paladino',
            4016 => 'Mestre',
            4017 => 'Professor',
            4018 => 'Desordeiro',
            4019 => 'Criador',
            4020 => 'Menestrel',
            4021 => 'Cigana',
        //4022 => 'Paladino (Peco)',

            4023 => 'Bebê',
            4024 => 'Espadachim Bebê',
            4025 => 'Mago Bebê',
            4026 => 'Arqueiro Bebê',
            4027 => 'Noviço Bebê',
            4028 => 'Mercador Bebê',
            4029 => 'Gatuno Bebê',
            4030 => 'Cavaleiro Bebê',
            4031 => 'Sacerdote Bebê',
            4032 => 'Bruxo Bebê',
            4033 => 'Ferreiro Bebê',
            4034 => 'Caçador Bebê',
            4035 => 'Mercenário Bebê',
        //4036 => 'Cavaleiro Bebê (Peco)',
            4037 => 'Templário Bebê',
            4038 => 'Monge Bebê',
            4039 => 'Sábio Bebê',
            4040 => 'Arruaceiro Bebê',
            4041 => 'Alquimista Bebê',
            4042 => 'Bardo Bebê',
            4043 => 'Odalisca Bebê',
        //4044 => 'Templário Bebê (Peco)',
            4045 => 'Super Aprendiz Bebê',

            4046 => 'Taekwon',
            4047 => 'Mestre Taekwon',
        //4048 => 'Mestre Taekwon (Voo)',
            4049 => 'Espiritualista',

            4050 => 'Jiang Shi',
            4051 => 'Death Knight',
            4052 => 'Dark Collector',

            4054 => 'Cavaleiro Rúnico',
            4055 => 'Arcano',
            4056 => 'Sentinela',
            4057 => 'Arcebispo',
            4058 => 'Mecânico',
            4059 => 'Sicário',
            4060 => 'Cavaleiro Rúnico T.',
            4061 => 'Arcano T.',
            4062 => 'Sentinela T.',
            4063 => 'Arcebispo T.',
            4064 => 'Mecânico T.',
            4065 => 'Sicário T.',
            4066 => 'Guardião Real',
            4067 => 'Feiticeiro',
            4068 => 'Trovador',
            4069 => 'Musa',
            4070 => 'Shura',
            4071 => 'Bioquímico',
            4072 => 'Renegado',
            4073 => 'Guardião Real T.',
            4074 => 'Feiticeiro T.',
            4075 => 'Trovador T.',
            4076 => 'Musa T.',
            4077 => 'Shura T.',
            4078 => 'Bioquímico T.',
            4079 => 'Renegado T.',

        //4080 => 'Cavaleiro Rúnico (Dragão)',
        //4081 => 'Cavaleiro Rúnico T. (Dragão)',
        //4082 => 'Guardião Real (Grifo)',
        //4083 => 'Guardião Real T. (Grifo)',
        //4084 => 'Sentinela (Lobo)',
        //4085 => 'Sentinela T. (Lobo)',
        //4086 => 'Mecânico (Robô)',
        //4087 => 'Mecânico T. (Robô)',

            4096 => 'Cavaleiro Rúnico Bebê',
            4097 => 'Arcano Bebê',
            4098 => 'Sentinela Bebê',
            4099 => 'Arcebispo Bebê',
            4100 => 'Mecânico Bebê',
            4101 => 'Sicário Bebê',
            4102 => 'Guardião Real Bebê',
            4103 => 'Feiticeiro Bebê',
            4104 => 'Trovador Bebê',
            4105 => 'Musa Bebê',
            4106 => 'Shura Bebê',
            4107 => 'Bioquímico Bebê',
            4108 => 'Renegado Bebê',

        //4109 => 'Cavaleiro Rúnico Bebê (Dragão)',
        //4110 => 'Guardião Real Bebê (Grifo)',
        //4111 => 'Sentinela Bebê (Lobo)',
        //4112 => 'Mecânico Bebê (Robô)',

            4190 => 'Super Aprendiz T.',
            4191 => 'Super Aprendiz Bebê T.',

            4211 => 'Kagerou',
            4212 => 'Oboro',

            4215 => 'Rebelde',
            4218 => 'Summoner',

            4220 => 'Summoner Bebê',
            4222 => 'Ninja Bebê',
            4223 => 'Kagero Bebê',
            4224 => 'Oboro Bebê',
            4225 => 'Taekwon Bebê',
            4226 => 'Mestre Taekwon Bebê',
            4227 => 'Espiritualista Bebê',
            4228 => 'Justiceiro Bebê',
            4229 => 'Rebellion Bebê',
        //4238 => 'Mestre Taekwon Bebê (União)',

        //4238 => 'Mestre Taekwon Bebê (União)',
            4239 => 'Star Emperor',
            4240 => 'Soul Reaper',
            4241 => 'Bebê Star Emperor',
            4242 => 'Bebê Soul Reaper',

            4252 => 'Dragon Knight',
            4253 => 'Meister',
            4254 => 'Shadow Cross',
            4255 => 'Arch Mage',
            4256 => 'Cardinal',
            4257 => 'WindHawk',
            4258 => 'Imperial Guard',
            4259 => 'Biolo',
            4260 => 'Abyss Chaser',
            4261 => 'Elemental Master',
            4262 => 'Inquisitor',
            4263 => 'Troubadour',
            4264 => 'Trouvere',
            4308 => 'Doram',
        ];
    }
    
function JobsAlchemist(){
    return [
    	18   => 'Alchemist',
    	4019 => 'Creator',
    	4041 => 'Baby Alchemist',
    	4071 => 'Genetic',
    	4078 => 'Genetic+',
    	4107 => 'Baby Genetic',
    	4259 => 'Biolo'
    ];
}    
function JobsBlacksmith(){
    return [
    	10   => 'Blacksmith',
    	4011 => 'Whitesmith',
    	4033 => 'Baby Blacksmith',
    	4058 => 'Mechanic',
    	4064 => 'Mechanic+',
    	4100 => 'Baby Mechanic',
    	4253 => 'Meister'
    ];
}

?>